parameters:
  - name: "storageAccountName" # Name of the terraform state storage account. Needs to be globally unique
    type: string
  - name: "resourceGroupName" # Name of the resource group where the state storage accounts gets created. Will be created if not exists
    type: string
  - name: "location"
    type: string

jobs:
  - job: Build
    pool: "Default"
    steps:
      # Check if Terraform state store exists and create it if not
      - task: AzureCLI@2
        displayName: "Setup Terraform state store"
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            ./scripts/create_state_store.ps1 -resourceGroupName $(resourceGroupName) -storageAccountName $(storageAccountName) -location $(location)
