trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: waitForValidation
  displayName: Wait for external validation
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 60
    inputs:
      notifyUsers: |
        waltonchiang@microsoft.com
      instructions: 'Please validate the build configuration and resume'
      onTimeout: 'reject'

# job to echo a message
- job: echoMessage
  dependsOn: waitForValidation
  displayName: Echo a message
  pool: Azure Pipelines
  steps:
  - script: echo 'Hello, world!'
    displayName: 'Run a one-line script'
